# Generated by Django 2.2.9 on 2021-11-25 12:26

from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211110_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.validators.validate_not_empty]),
        ),
    ]
